name: Autostyle
on: [push, pull_request]
jobs:
  autostlye:
    name: "Spotless"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Check
        run: ./gradlew spotlessCheck -PspotlessRatchet=false
